FROM codercom/code-server:latest

USER root

# Install the Jupyter extension
# https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
RUN code-server --install-extension ms-toolsai.jupyter

USER coder
