FROM codercom/code-server:4.16.1

# Install the extensions
# https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter@2023.4.1001091014
# https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-powertoys
RUN code-server --install-extension ms-toolsai.jupyter --install-extension ms-toolsai.vscode-jupyter-powertoys --install-extension ms-python.python
